"""Project + competitor CRUD (tenant-scoped)."""

from __future__ import annotations

from fastapi import APIRouter, Depends, Response
from sqlalchemy.orm import Session

from app.api.deps import get_current_tenant, owned_project
from app.db.session import get_db
from app.models.geo import GeoResult
from app.models.project import Competitor, Project
from app.models.prompt import Prompt
from app.models.serp import SerpQuery
from app.models.tenant import Tenant
from app.schemas.project import ProjectIn, ProjectOut
from app.services.exports.prompts import build_prompts_excel, build_prompts_pdf

router = APIRouter(prefix="/projects", tags=["projects"])


@router.get("", response_model=list[ProjectOut])
def list_projects(
    db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> list[Project]:
    return (
        db.query(Project)
        .filter(Project.tenant_id == tenant.id)
        .order_by(Project.created_at.desc())
        .all()
    )


@router.post("", response_model=ProjectOut, status_code=201)
def create_project(
    payload: ProjectIn, db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> Project:
    project = Project(
        tenant_id=tenant.id,
        name=payload.name,
        target_url=payload.target_url,
        industry=payload.industry,
        notes=payload.notes,
        competitors=[Competitor(name=c.name, url=c.url) for c in payload.competitors],
    )
    db.add(project)
    db.commit()
    db.refresh(project)
    return project


@router.get("/{project_id}", response_model=ProjectOut)
def get_project(
    project_id: int, db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> Project:
    return owned_project(db, project_id, tenant)


@router.delete("/{project_id}", status_code=204, response_class=Response)
def delete_project(
    project_id: int, db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> Response:
    project = owned_project(db, project_id, tenant)
    db.delete(project)
    db.commit()
    return Response(status_code=204)


@router.get("/{project_id}/serp-queries")
def list_serp_queries(
    project_id: int, query_type: str | None = None, db: Session = Depends(get_db),
    tenant: Tenant = Depends(get_current_tenant),
) -> list[dict]:
    """PAA + featured-snippet seeds captured during Keyword Universe (for Phase 5)."""
    owned_project(db, project_id, tenant)
    q = db.query(SerpQuery).filter(SerpQuery.project_id == project_id)
    if query_type:
        q = q.filter(SerpQuery.query_type == query_type)
    rows = q.order_by(SerpQuery.is_question.desc(), SerpQuery.volume.desc().nullslast()).all()
    return [
        {
            "id": r.id, "query": r.query, "query_type": r.query_type,
            "is_question": r.is_question, "volume": r.volume,
            "difficulty": r.difficulty, "ranking_url": r.ranking_url,
            "seed_keyword": r.seed_keyword,
        }
        for r in rows
    ]


def _prompt_rows(db: Session, project_id: int) -> list[dict]:
    rows = (
        db.query(Prompt)
        .filter(Prompt.project_id == project_id)
        .order_by(Prompt.intent_bucket, Prompt.id)
        .all()
    )
    return [
        {"id": r.id, "text": r.text, "intent_bucket": r.intent_bucket, "source": r.source}
        for r in rows
    ]


@router.get("/{project_id}/prompts")
def list_prompts(
    project_id: int, db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> list[dict]:
    """Target prompts generated by module 7 (Prompt Identification)."""
    owned_project(db, project_id, tenant)
    return _prompt_rows(db, project_id)


@router.get("/{project_id}/prompts/export.xlsx")
def export_prompts_excel(
    project_id: int, db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> Response:
    project = owned_project(db, project_id, tenant)
    data = build_prompts_excel(_prompt_rows(db, project_id), project.name)
    return Response(
        content=data,
        media_type="application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
        headers={"Content-Disposition": 'attachment; filename="prompt_targets.xlsx"'},
    )


@router.get("/{project_id}/prompts/export.pdf")
def export_prompts_pdf(
    project_id: int, db: Session = Depends(get_db), tenant: Tenant = Depends(get_current_tenant)
) -> Response:
    project = owned_project(db, project_id, tenant)
    data = build_prompts_pdf(_prompt_rows(db, project_id), project.name)
    return Response(
        content=data, media_type="application/pdf",
        headers={"Content-Disposition": 'attachment; filename="prompt_targets.pdf"'},
    )


@router.get("/{project_id}/geo-results")
def list_geo_results(
    project_id: int, provider: str | None = None, db: Session = Depends(get_db),
    tenant: Tenant = Depends(get_current_tenant),
) -> list[dict]:
    """Per-prompt GEO results (module 8), with the API/SERP source flagged."""
    owned_project(db, project_id, tenant)
    q = db.query(GeoResult).filter(GeoResult.project_id == project_id)
    if provider:
        q = q.filter(GeoResult.provider == provider)
    rows = q.order_by(GeoResult.provider, GeoResult.id).all()
    return [
        {
            "id": r.id, "provider": r.provider, "source_kind": r.source_kind,
            "prompt": r.prompt_text, "client_mentioned": r.client_mentioned,
            "client_cited": r.client_cited, "client_position": r.client_position,
        }
        for r in rows
    ]
