"""serp_queries

Revision ID: 64234abde401
Revises: 9d1ef1169bbe
Create Date: 2026-06-29 10:36:57.506301
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64234abde401'
down_revision: Union[str, None] = '9d1ef1169bbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('serp_queries',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('query', sa.String(length=512), nullable=False),
    sa.Column('query_type', sa.String(length=32), nullable=False),
    sa.Column('seed_keyword', sa.String(length=512), nullable=True),
    sa.Column('is_question', sa.Boolean(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=True),
    sa.Column('difficulty', sa.Float(), nullable=True),
    sa.Column('ranking_url', sa.String(length=2048), nullable=True),
    sa.Column('source', sa.String(length=32), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('project_id', 'query', 'query_type', name='uq_serp_project_query_type')
    )
    with op.batch_alter_table('serp_queries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_serp_queries_is_question'), ['is_question'], unique=False)
        batch_op.create_index(batch_op.f('ix_serp_queries_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('serp_queries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_serp_queries_project_id'))
        batch_op.drop_index(batch_op.f('ix_serp_queries_is_question'))

    op.drop_table('serp_queries')
    # ### end Alembic commands ###
