"""crawl jobs and pages

Revision ID: 9d1ef1169bbe
Revises: 9d6c73403403
Create Date: 2026-06-29 10:05:13.928458
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d1ef1169bbe'
down_revision: Union[str, None] = '9d6c73403403'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_jobs',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('source_type', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('input_json', sa.Text(), nullable=True),
    sa.Column('total', sa.Integer(), nullable=False),
    sa.Column('processed', sa.Integer(), nullable=False),
    sa.Column('message', sa.String(length=512), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('events_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_jobs_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_crawl_jobs_status'), ['status'], unique=False)

    op.create_table('pages',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('crawl_job_id', sa.Integer(), nullable=False),
    sa.Column('competitor_id', sa.Integer(), nullable=True),
    sa.Column('matched_page_id', sa.Integer(), nullable=True),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('is_competitor', sa.Boolean(), nullable=False),
    sa.Column('rank_score', sa.Float(), nullable=True),
    sa.Column('rank_reasons', sa.Text(), nullable=True),
    sa.Column('selected', sa.Boolean(), nullable=False),
    sa.Column('fetch_method', sa.String(length=16), nullable=True),
    sa.Column('http_status', sa.Integer(), nullable=True),
    sa.Column('fetch_ok', sa.Boolean(), nullable=False),
    sa.Column('fetch_error', sa.Text(), nullable=True),
    sa.Column('raw_html_path', sa.String(length=1024), nullable=True),
    sa.Column('content_hash', sa.String(length=64), nullable=True),
    sa.Column('cleaned_text', sa.Text(), nullable=True),
    sa.Column('title', sa.String(length=1024), nullable=True),
    sa.Column('meta_description', sa.Text(), nullable=True),
    sa.Column('word_count', sa.Integer(), nullable=True),
    sa.Column('signals_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['competitor_id'], ['competitors.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['crawl_job_id'], ['crawl_jobs.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['matched_page_id'], ['pages.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_pages_competitor_id'), ['competitor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_crawl_job_id'), ['crawl_job_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_is_competitor'), ['is_competitor'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_project_id'), ['project_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_selected'), ['selected'], unique=False)
        batch_op.create_index(batch_op.f('ix_pages_url'), ['url'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_pages_url'))
        batch_op.drop_index(batch_op.f('ix_pages_selected'))
        batch_op.drop_index(batch_op.f('ix_pages_project_id'))
        batch_op.drop_index(batch_op.f('ix_pages_is_competitor'))
        batch_op.drop_index(batch_op.f('ix_pages_crawl_job_id'))
        batch_op.drop_index(batch_op.f('ix_pages_competitor_id'))

    op.drop_table('pages')
    with op.batch_alter_table('crawl_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_status'))
        batch_op.drop_index(batch_op.f('ix_crawl_jobs_project_id'))

    op.drop_table('crawl_jobs')
    # ### end Alembic commands ###
