"""initial schema

Revision ID: 9d6c73403403
Revises: 
Create Date: 2026-06-29 09:51:46.905425
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d6c73403403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('api_cache',
    sa.Column('cache_key', sa.String(length=128), nullable=False),
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('endpoint', sa.String(length=512), nullable=False),
    sa.Column('request_params', sa.Text(), nullable=True),
    sa.Column('response_body', sa.Text(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_cache_cache_key'), ['cache_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_cache_provider'), ['provider'], unique=False)

    op.create_table('api_keys',
    sa.Column('provider', sa.String(length=64), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=True),
    sa.Column('encrypted_value', sa.Text(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('provider', name='uq_api_keys_provider')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_provider'), ['provider'], unique=False)

    op.create_table('benchmark_sources',
    sa.Column('metric', sa.String(length=255), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=64), nullable=True),
    sa.Column('source_name', sa.String(length=512), nullable=False),
    sa.Column('source_url', sa.String(length=2048), nullable=True),
    sa.Column('source_year', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('metric', 'industry', name='uq_benchmark_metric_industry')
    )
    with op.batch_alter_table('benchmark_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_benchmark_sources_industry'), ['industry'], unique=False)
        batch_op.create_index(batch_op.f('ix_benchmark_sources_metric'), ['metric'], unique=False)

    op.create_table('projects',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('industry', sa.String(length=255), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('analysis_runs',
    sa.Column('project_id', sa.Integer(), nullable=True),
    sa.Column('module', sa.String(length=64), nullable=False),
    sa.Column('scope', sa.String(length=8), nullable=False),
    sa.Column('target_url', sa.String(length=2048), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=8), nullable=True),
    sa.Column('result_json', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_analysis_runs_module'), ['module'], unique=False)
        batch_op.create_index(batch_op.f('ix_analysis_runs_project_id'), ['project_id'], unique=False)

    op.create_table('competitors',
    sa.Column('project_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('url', sa.String(length=2048), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_competitors_project_id'), ['project_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('competitors', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_competitors_project_id'))

    op.drop_table('competitors')
    with op.batch_alter_table('analysis_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_analysis_runs_project_id'))
        batch_op.drop_index(batch_op.f('ix_analysis_runs_module'))

    op.drop_table('analysis_runs')
    op.drop_table('projects')
    with op.batch_alter_table('benchmark_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_benchmark_sources_metric'))
        batch_op.drop_index(batch_op.f('ix_benchmark_sources_industry'))

    op.drop_table('benchmark_sources')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_provider'))

    op.drop_table('api_keys')
    with op.batch_alter_table('api_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_cache_provider'))
        batch_op.drop_index(batch_op.f('ix_api_cache_cache_key'))

    op.drop_table('api_cache')
    # ### end Alembic commands ###
